version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_CONTAINER_NAME}
    image: ${APP_IMAGE_NAME}
    ports:
      - "${APP_PORT}:5000"
    volumes:
      - ./:/app
    depends_on:
      - db
    tty: true
    restart: unless-stopped

  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    restart: unless-stopped

  db_admin:
    container_name: ${DB_ADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4:6.1
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
      GUNICORN_ACCESS_LOGFILE: /var/lib/pgadmin/logs.txt
    ports:
      - "${DB_ADMIN_PORT}:80"
    restart: unless-stopped
